### ISSUE TITLE
Elasticsearch plugin - monitoring if a node is alive?

### ISSUE THREAD

**Issue by danwashusen** [threelegs/newrelic-plugins#37]
Quick question (and I'm new to newrelic so maybe I'm missing something), does the elasticsearch plugin monitor and report on the state of the node (up/down)?

I have a three node cluster with the following config:

```
  elasticsearch:
    - name: db-01
      host: db-01
      port: 9200
      scheme: http
    - name: db-02
      host: db-02
      port: 9200
      scheme: http
    - name: db-03
      host: db-03
      port: 9200
      scheme: http
```

To test I shut down db-03 and waited for ~10 minutes but the new relic UI is still reporting 'Component normal'. I was hoping the plugin would alert me of this?

As a side question/alternative, I can't seem to create an alert on based on the number of data nodes (under the 'Cluster' tab)?
